apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
        - image: localhost:5000/<image_url>
          imagePullPolicy: Always
          name: api1
          ports:
            - name: api
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api1
  labels:
    app: api1
    type: microservice
    release: app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: api
  selector:
    app: api1